name: newspp_desktop_backend
description: "Backend for newspp."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  file_picker: ^10.3.1
  toastification: ^3.0.3
  path: ^1.9.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  html: ^0.15.6
  tesseract_ocr: ^0.5.0
  window_manager: ^0.5.1
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  encrypt: ^5.0.3
  intl: ^0.20.2
  calendar_date_picker2: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/bin/windows/pdf2htmlex/data/
    - assets/bin/windows/pdf2htmlex/pdf2htmlEX.exe
    - assets/tessdata_config.json
    - assets/bin/windows/convert.exe
    - assets/bin/windows/poppler/bin/
    - assets/bin/windows/compress.exe
